### ISSUE TITLE
Router reuses a component instance even if the corresponding option is disabled

### ISSUE THREAD

**Issue by Serhii-the-Dev** [rdkcentral/Lightning-SDK#269] opened 2021-10-18 13:54 UTC
Given such a Router config:
```js
export default {
  root: 'app/catalog/home',
  routes: [
    {
      path: 'app/video/:videoId',
      component: Video,
      options: {
        reuseInstance: false,
      },
    },
    {
      path: 'app/:entityType/:entityId',
      component: Page,
      options: {
        reuseInstance: false,
      },
    },
  ],
}
```
and the next navigation chain setup: `Page` -> `Page` -> `Video`, the forward navigation works just fine, however while moving backwards a first encountered `Page` will be reused. It makes impossible to rely on any component lifecycle hooks (like `_active`) or use animated transitions between screens.

**Comment by michielvandergeest** [comment] 2022-04-12 08:29
We have tried this recently but were not able to reproduce the issue anymore.

I'm closing this issue, but feel to re-open if this is still an issue with the latest version of the SDK, preferably with a test project that showcases the issue.

**Closed as completed by michielvandergeest** 2022-04-12 08:29 UTC
