### ISSUE TITLE
Router boot page/splash screen (bootComponent/`#$`) gets stuck and never proceeds to root page

### ISSUE THREAD

**Issue by aposmontier** [rdkcentral/Lightning-SDK#351] opened 2022-10-04 19:06 UTC
In certain scenarios, the page specified in Router configuration as a [Boot page](https://lightningjs.io/docs/#/lightning-sdk-reference/plugins/router/configuration?id=bootpage) can be loaded after the Router is started (most commonly, if the WPE browser's back function or the equivalent keyboard shortcut is used). In this case, the entire app will be stuck on the splash screen, since the Router only checks for completion of the [`boot`](https://lightningjs.io/docs/#/lightning-sdk-reference/plugins/router/configuration?id=boot) callback once, when the app first loads and calls `startRouter()`. 

While this is certainly an edge case, it's definitely possible that either app code or the browser changes the hash to `#$`, and the Router should handle this gracefully. One possible approach would be to hold onto the promise returned by the configured `boot` callback, and if the hash is changed back to `#$` and the `boot` promise is already resolved, simply proceed back to the `root` component of the app. I am only slightly familiar with Router internals, but I am happy to make a PR for this as a starting point. I think this would just require holding onto the return value of `boot`, and an extra check in `handleHashChange` for the special `#$` route.

**Comment by michielvandergeest** [comment] 2022-11-14 11:05
Hi @aposmontier we have been looking into this issue, but so far we couldn't reproduce the exact case.
By any chance would you be able to share an example App or a video clearly displaying the issue? That would be really helpful :)

**Comment by sandeep-vedam** [comment] 2023-06-28 10:24
Hello @aposmontier,

We hope this message finds you well. After carefully reviewing this particular issue's progress, it appears there haven't been any recent updates. Therefore, we regret to inform you that we have decided to close this issue for now. However, we want to assure you that we're here to assist you if needed.

To better understand and address the issue you encountered, we kindly request your assistance. If you could provide us with a sample app or a video that clearly illustrates the problem, we would greatly appreciate it. By sharing this additional information, you can help us reopen the issue and work towards finding a resolution.

Thank you for your understanding and cooperation. We look forward to hearing from you soon.

**Closed by sandeep-vedam** 2023-06-28 10:24 UTC
Labels: needs-reproduction
